;; -*- mode: eask; lexical-binding: t -*-

(package "google-gemini"
         "0.1.0"
         "Elisp library for the Google Gemini API")

(website-url "https://github.com/emacs-openai/google-gemini")
(keywords "comm" "google" "gemini")

(package-file "google-gemini.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)
(source 'jcs-elpa)

(depends-on "emacs" "26.1")
(depends-on "request")
(depends-on "tblui")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
